#pragma kernel CSMain

RWTexture2D<float4> Result;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float4 baseColor = float4(id.x & id.y, (id.x & 15) / 15.0, (id.y & 15) / 15.0, 1.0);
    float4 color = Result[id.xy];
	
    //Rainbow color
    color.r += 0.01f;
    color.g += 0.005f;
    color.b += 0.008f;
    color = frac(color);
	
    Result[id.xy] = float4(color) + baseColor * 0.5f;
}


